// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoLwXMz04ou3MYfVUnKGwgcsaOjdfwTbU',
    appId: '1:636449180603:web:62168e36f05d6c2b94d29e',
    messagingSenderId: '636449180603',
    projectId: 'pet-feeding-app',
    authDomain: 'pet-feeding-app.firebaseapp.com',
    databaseURL: 'https://pet-feeding-app-default-rtdb.firebaseio.com',
    storageBucket: 'pet-feeding-app.firebasestorage.app',
    measurementId: 'G-G11D4Y0XVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnfGty1uwH8YXVuWiIoOqCBvd0TeevzQI',
    appId: '1:636449180603:android:90757128f361147594d29e',
    messagingSenderId: '636449180603',
    projectId: 'pet-feeding-app',
    databaseURL: 'https://pet-feeding-app-default-rtdb.firebaseio.com',
    storageBucket: 'pet-feeding-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvuvAni-YuiWUBH7RjznFD76ukjIkTJu4',
    appId: '1:636449180603:ios:8563f8f7b842c3da94d29e',
    messagingSenderId: '636449180603',
    projectId: 'pet-feeding-app',
    databaseURL: 'https://pet-feeding-app-default-rtdb.firebaseio.com',
    storageBucket: 'pet-feeding-app.firebasestorage.app',
    androidClientId: '636449180603-ko9nmg29bgtppvj8uqfhb421rlrgsbdj.apps.googleusercontent.com',
    iosClientId: '636449180603-82tv4ej8as6ghbeon48vacuato3n99ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.petFeederApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvuvAni-YuiWUBH7RjznFD76ukjIkTJu4',
    appId: '1:636449180603:ios:8563f8f7b842c3da94d29e',
    messagingSenderId: '636449180603',
    projectId: 'pet-feeding-app',
    databaseURL: 'https://pet-feeding-app-default-rtdb.firebaseio.com',
    storageBucket: 'pet-feeding-app.firebasestorage.app',
    androidClientId: '636449180603-ko9nmg29bgtppvj8uqfhb421rlrgsbdj.apps.googleusercontent.com',
    iosClientId: '636449180603-82tv4ej8as6ghbeon48vacuato3n99ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.petFeederApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoLwXMz04ou3MYfVUnKGwgcsaOjdfwTbU',
    appId: '1:636449180603:web:a7433e3d517131ab94d29e',
    messagingSenderId: '636449180603',
    projectId: 'pet-feeding-app',
    authDomain: 'pet-feeding-app.firebaseapp.com',
    databaseURL: 'https://pet-feeding-app-default-rtdb.firebaseio.com',
    storageBucket: 'pet-feeding-app.firebasestorage.app',
    measurementId: 'G-ZXQGQEJ5T9',
  );
}
